// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ValePedagio.Infrastructure.Persistence;

#nullable disable

namespace ValePedagio.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ValePedagioDbContext))]
internal sealed class ValePedagioDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("ValePedagio.Domain.ValePedagioProviderConfiguration", b =>
        {
            b.Property<string>("TenantId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("Provider")
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("CallbackMode")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<System.Collections.Generic.Dictionary<string, string>>("Credentials")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<string>("DisplayName")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<bool>("Enabled")
                .HasColumnType("boolean");

            b.Property<string>("EndpointBaseUrl")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("Wave")
                .HasColumnType("integer");

            b.HasKey("TenantId", "Provider");

            b.HasIndex("TenantId");

            b.ToTable("vale_pedagio_provider_configurations", (string)null);
        });

        modelBuilder.Entity("ValePedagio.Domain.ValePedagioSolicitacao", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedNever()
                .HasColumnType("uuid");

            b.Property<System.Collections.Generic.List<ValePedagio.Domain.ValePedagioAuditTrail>>("AuditTrail")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<string>("CallbackUrl")
                .HasMaxLength(1024)
                .HasColumnType("character varying(1024)");

            b.Property<System.Collections.Generic.List<string>>("CteIds")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("DocumentoResponsavelPagamento")
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<decimal>("EstimatedCargoValue")
                .HasColumnType("numeric");

            b.Property<string>("FailureReason")
                .HasMaxLength(4000)
                .HasColumnType("character varying(4000)");

            b.Property<string>("MotoristaId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("NumeroCompra")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("Observacoes")
                .HasMaxLength(4000)
                .HasColumnType("character varying(4000)");

            b.Property<string>("Protocolo")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("Provider")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("RawRequestPayload")
                .HasColumnType("text");

            b.Property<string>("RawResponsePayload")
                .HasColumnType("text");

            b.Property<System.Collections.Generic.List<ValePedagio.Domain.ValePedagioRegulatoryItem>>("RegulatoryItems")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<ValePedagio.Domain.ValePedagioReceipt>("Receipt")
                .HasColumnType("jsonb");

            b.Property<int>("RetryCount")
                .HasColumnType("integer");

            b.Property<ValePedagio.Domain.ValePedagioRoute>("Route")
                .IsRequired()
                .HasColumnType("jsonb");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(32)
                .HasColumnType("character varying(32)");

            b.Property<string>("TenantId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<string>("TransportadorId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<decimal?>("ValorTotal")
                .HasColumnType("numeric");

            b.Property<string>("VeiculoId")
                .HasMaxLength(128)
                .HasColumnType("character varying(128)");

            b.HasKey("Id");

            b.HasIndex("TenantId", "CreatedAt");

            b.HasIndex("TenantId", "Provider", "Status");

            b.ToTable("vale_pedagio_solicitacoes", (string)null);
        });
#pragma warning restore 612, 618
    }
}
